import { applySuggestionToCard, embedCardJsonInPng, extractCardJsonFromPng, scoreCard } from "./scorer.mjs";
import { mergeFindings } from "./merge-findings.mjs";
import { describeReviewerMiss, filterAiSuggestions, isDraftableField } from "./ai-review.mjs";
import { accentFromImage } from "./art-accent.mjs";
import { connectPersistedSettings, readAiSettings } from "./review-settings.mjs";
import { exportReadiness } from "./export-readiness.mjs";
import { createBulkStore } from "./bulk-store.mjs";
import { buildRecord, readCardFile, scanFiles } from "./bulk-scan.mjs";

const $ = (s) => document.querySelector(s); const file = $('#card-file'), review = $('#review'), empty = $('#empty-state');
let text = '', sourcePng = null, result = null, applied = [], gateOpen = false, previous = null, ledger = [], targetModel = localStorage.getItem('cq.model') || 'any', creatorDirection = localStorage.getItem('cq.direction') || 'true', accent = '#dfa04f';
const store = createBulkStore();
// Write the live working vars into the active record (call before switching cards).
function saveActive(){const rec=store.active();if(!rec)return;Object.assign(rec,{text,sourcePng,result,applied:[...applied],gateOpen,previous,ledger:[...ledger],name:result?result.name:rec.name,edited:rec.edited||applied.length>0});}
// Load a record's fields into the live working vars (call after switching cards).
function hydrate(rec){text=rec.text;sourcePng=rec.sourcePng;result=rec.result;applied=[...rec.applied];gateOpen=rec.gateOpen;previous=rec.previous;ledger=[...rec.ledger];}
const sample = {spec:'chara_card_v2',spec_version:'2.0',data:{name:'Mara Venn',description:'Mara Venn is a retired courier from the brass city of Leth, known for memorizing routes through storms and border posts. She keeps coded maps inside her cuffs and refuses to abandon clients.',personality:'Warm but guarded, generous but allergic to sentimentality. She jokes when frightened and hates unpaid debts.',scenario:'{{user}} meets Mara at a shuttered station while a dust storm traps both of them inside. Someone outside knocks in a pattern Mara recognizes.',first_mes:'*Mara lowers the lantern.* "If you are here because of that knocking, answer quickly: did you hear three taps or four?"',mes_example:'<START>\n{{user}}: Why does the tapping matter?\n{{char}}: "Three means shelter. Four means danger."',creator_notes:'Tense travel and mystery.',tags:['mystery','mentor'],extensions:{}}};
connectPersistedSettings($);
file.addEventListener('change', async () => { if(file.files[0]) await load(file.files[0]); }); $('#sample-button').onclick=()=>{const rec=store.add(buildRecord({fileName:'mara-sample.json',text:JSON.stringify(sample),sourcePng:null}));store.setActive(rec.id);store.setWorklist([rec.id]);hydrate(rec);$('#card-art').hidden=true;$('#art-placeholder').hidden=false;showReview();afterAnalyze()}; $('#settings-button').onclick=()=>$('#settings').showModal(); $('#fetch-models-button').onclick=fetchModels; $('#download-button').onclick=downloadJson; $('#download-png-button').onclick=downloadPng; $('#undo-button').onclick=undo;
$('#reanalyze-button').onclick=()=>{gateOpen=true;render();announce('Improvements unlocked.');}; $('#calm').onchange=(e)=>{document.documentElement.style.setProperty('--accent',e.target.checked?'#dfa04f':accent)};
for(const b of $('#model-controls').children)b.onclick=()=>{targetModel=b.dataset.model;localStorage.setItem('cq.model',targetModel);render()}; for(const b of $('#direction-controls').children)b.onclick=()=>{creatorDirection=b.dataset.direction;localStorage.setItem('cq.direction',creatorDirection);render()};
async function load(input){try{const {text:t,sourcePng:png}=await readCardFile(input);const rec=store.add(buildRecord({fileName:input.name,text:t,sourcePng:png}));store.setActive(rec.id);store.setWorklist([rec.id]);hydrate(rec);if(png){const image=$('#card-art');image.src=URL.createObjectURL(new Blob([png.bytes],{type:'image/png'}));image.onload=()=>{const colors=accentFromImage(image);accent=colors.accent;if(!$('#calm').checked)document.documentElement.style.setProperty('--accent',colors.accent);document.documentElement.style.setProperty('--bright',colors.bright)};image.hidden=false;$('#art-placeholder').hidden=true}else{$('#card-art').hidden=true;$('#art-placeholder').hidden=false}showReview();afterAnalyze()}catch(e){showError(e)}}
function analyze(){try{result=scoreCard(text);applied=[];gateOpen=false;ledger=[`${result.total} · loaded`];afterAnalyze()}catch(e){showError(e)}}
function afterAnalyze(){empty.hidden=true;review.hidden=false;$('#gate').hidden=false;setJourney('review');render();announce(`Scored ${result.total}.`);saveActive()}
function showReview(){}  // replaced in Task 6
function setJourney(where){for(const j of document.querySelectorAll('.journey'))j.classList.toggle('active',j.dataset.jump===where)}
for(const b of document.querySelectorAll('.journey'))b.onclick=()=>{if(b.dataset.jump==='load'){file.click();return}const t=b.dataset.jump==='export'?$('#export'):$('#review');if(t&&!t.hidden){setJourney(b.dataset.jump);t.scrollIntoView({block:'start'})}};
function spyJourney(){if(review.hidden)return;const exp=$('#export');const mid=window.scrollY+window.innerHeight/2;const atBottom=window.innerHeight+window.scrollY>=document.documentElement.scrollHeight-4;setJourney(exp&&(atBottom||exp.offsetTop<=mid)?'export':'review')}
window.addEventListener('scroll',spyJourney,{passive:true});
$('#ship-export').onclick=()=>{setJourney('export');const t=$('#export');if(t&&!t.hidden)t.scrollIntoView({block:'start'})};
function plan(){return mergeFindings(result.reviewFindings,{targetModel,appliedFindingIds:applied,gateOpen})}
function render(){const p=plan(), score=result.total; $('#score').textContent=score;$('#band').textContent=result.band;const ship=exportReadiness(result.band);$('#ship-banner').hidden=!(ship.ready&&p.blockers.length===0);$('#ship-message').textContent=ship.message;const who=(result.name||'').trim()||'This card';$('#headline').textContent=p.blockers.length?`${who} — ${p.blockers.length} field${p.blockers.length>1?'s':''} ${p.blockers.length>1?'block':'blocks'} the card. Start there.`:p.gate.open?`${who} is close. Shape the remaining details.`:`${who}'s blockers are cleared. Re-analyze to open the queue.`;$('#summary').textContent=`${result.summary} The list below orders what to fix first.`;$('#criteria').replaceChildren(...result.criteria.map(c=>el('div','criterion',`<span>${c.label}<br><small>${c.note}</small></span><b>${c.points}/${c.max}</b>`)));setControls();$('#blocker-caption').textContent=p.blockers.length?`${p.blockers.length} blocker${p.blockers.length>1?'s':''}`:'';$('#blockers').replaceChildren(...p.blockers.map(card=>fieldCard(card)));$('#gate-title').textContent=p.gate.open?'✓ Unlocked — improvements are actionable':'🔒 Improvements are waiting';$('#gate-copy').textContent=p.gate.reason;$('#locked-improvements').replaceChildren(...p.improvements.map(c=>{const canShowDraft=p.gate.open||c.fixTemplate;const d=el('div',canShowDraft?'':'locked');if(canShowDraft)d.append(fieldCard(c,'improvement'));else d.textContent=`~+${c.leverage} pts · ${c.title}`;return d}));$('#reanalyze-button').disabled=p.blockers.length>0;$('#polish-summary').textContent=`${p.advisories.length} polish note${p.advisories.length===1?'':'s'} — advice only, never counted`;$('#advisories').replaceChildren(...p.advisories.map(f=>el('div','advisory',`<b>${f.field}</b> · ${f.summary}`)));$('#ledger').hidden=ledger.length<2;$('#ledger-items').replaceChildren(...ledger.map(x=>el('span','',x)));$('#undo-button').disabled=!previous;$('#download-png-button').disabled=!sourcePng}
function setControls(){for(const b of $('#model-controls').children)b.classList.toggle('active',b.dataset.model===targetModel);for(const b of $('#direction-controls').children)b.classList.toggle('active',b.dataset.direction===creatorDirection)}
function fieldCard(card,kind=''){const node=el('article',`field-card ${kind}`);node.innerHTML=`<div class="field-head"><span class="pill">${card.field}</span><strong>${card.title}</strong><span class="leverage">~+${card.leverage} pts</span></div>`;for(const f of card.findings)node.append(el('div','finding-row',`<b>${f.source}</b><span>${f.summary}</span>`));const area=document.createElement('textarea');area.value=card.fixTemplate||'';area.placeholder='This needs a real character-specific draft. Use the reviewer to write one from the card evidence.';node.append(area);const actions=el('div','actions');const apply=el('button','', 'Apply');apply.disabled=!area.value;apply.onclick=()=>applyCard(card,area.value);area.oninput=()=>nodeEnable(area);actions.append(apply);const status=el('div','ask-status');status.setAttribute('role','status');if(isDraftableField(card.field)){const ask=el('button','ask',card.fixTemplate?'Improve with reviewer →':'Draft with reviewer →');ask.dataset.label=ask.textContent;ask.onclick=()=>askReviewer(card,area,ask,status);actions.append(ask)}node.append(actions,status);return node}
function applyCard(card,draft){previous={text,applied:[...applied],gateOpen,ledger:[...ledger]};text=JSON.stringify(applySuggestionToCard(text,{field:card.field,draft}),null,2);applied.push(...card.findings.map(f=>f.id));result=scoreCard(text);store.active().edited=true;ledger.push(`+${card.title.toLowerCase()} → ${result.total}`);gateOpen=!result.reviewFindings.some(f=>f.severity==='blocker'&&!applied.includes(f.id));render();announce(`${card.title} applied as one change.`);saveActive()}function undo(){if(!previous)return;text=previous.text;applied=previous.applied;gateOpen=previous.gateOpen;ledger=previous.ledger;result=scoreCard(text);previous=null;render();announce('Last combined change undone.');saveActive()}
async function askReviewer(card,area,button,status){const label=button.dataset.label;button.disabled=true;const t0=Date.now();button.textContent='The reviewer is reading… 0s';const tick=setInterval(()=>{button.textContent=`The reviewer is reading… ${Math.round((Date.now()-t0)/1000)}s`},1000);status.textContent='';status.classList.remove('error');const validFindingIds=card.findings.map(f=>f.id);try{const r=await fetch('/api/ai-review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({card:text,aiConfig:settings(),findings:card.findings,targetField:card.field,validFindingIds,creatorDirection,targetModel,mode:'review'})});const payload=await r.json();if(!r.ok)throw Error(payload.error);const all=payload.suggestions||[];const drafts=filterAiSuggestions(all,new Set(validFindingIds),new Set([card.field]));if(!drafts.length){button.textContent=label;status.classList.add('error');status.textContent=describeReviewerMiss(all,card.field);return}area.value=drafts[0].draft;button.textContent=drafts[0].directionUsed?'AI draft · direction used':'AI draft · grounded';nodeEnable(area)}catch(e){button.textContent=label;status.classList.add('error');status.textContent=e.message||'Reviewer unavailable'}finally{clearInterval(tick);button.disabled=false}}
async function fetchModels(){const button=$('#fetch-models-button'),status=$('#models-status'),list=$('#model-options'),model=$('#ai-model');button.disabled=true;status.textContent='Fetching models…';try{const r=await fetch('/api/models',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({aiConfig:settings()})});const payload=await r.json();if(!r.ok)throw Error(payload.error);const models=Array.isArray(payload.models)?payload.models:[];list.replaceChildren(...models.map(id=>{const option=document.createElement('option');option.value=id;return option}));if(models.length&&!model.value.trim())model.value=models[0];status.textContent=models.length?`Loaded ${models.length} models. Pick one from the Model field.`:'No models returned.'}catch(e){status.textContent=e.message||'Could not fetch models.'}finally{button.disabled=false}}
function nodeEnable(area){area.parentElement.querySelector('.actions button').disabled=!area.value}function settings(){return readAiSettings($)}function announce(m){$('#live').textContent=m}function showError(e){empty.hidden=true;review.hidden=false;$('#headline').textContent="I couldn't read this card.";$('#summary').textContent=e.message||'Check that this is valid JSON or a PNG with embedded card data.';$('#blockers').replaceChildren();$('#gate').hidden=true;announce('Card load error.')}function el(tag,cls,html=''){const n=document.createElement(tag);n.className=cls;n.innerHTML=html;return n}function cardSlug(){return (result?.name||'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,60)||'character-card'}function downloadJson(){blob(text,`${cardSlug()}.json`,'application/json')}function downloadPng(){if(!sourcePng)return;blob(embedCardJsonInPng(sourcePng.bytes,text),`${cardSlug()}.png`,'image/png')}function blob(data,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
