import { applySuggestionToCard, embedCardJsonInPng, extractCardJsonFromPng, scoreCard } from "./scorer.mjs";
import { mergeFindings } from "./merge-findings.mjs";
import { describeReviewerMiss, filterAiSuggestions } from "./ai-review.mjs";
import { accentFromImage } from "./art-accent.mjs";
import { connectPersistedSettings, readAiSettings } from "./review-settings.mjs";

const $ = (s) => document.querySelector(s); const file = $('#card-file'), review = $('#review'), empty = $('#empty-state');
let text = '', sourcePng = null, result = null, applied = [], gateOpen = false, previous = null, ledger = [], targetModel = localStorage.getItem('cq.model') || 'any', creatorDirection = localStorage.getItem('cq.direction') || 'true', accent = '#dfa04f';
const sample = {spec:'chara_card_v2',spec_version:'2.0',data:{name:'Mara Venn',description:'Mara Venn is a retired courier from the brass city of Leth, known for memorizing routes through storms and border posts. She keeps coded maps inside her cuffs and refuses to abandon clients.',personality:'Warm but guarded, generous but allergic to sentimentality. She jokes when frightened and hates unpaid debts.',scenario:'{{user}} meets Mara at a shuttered station while a dust storm traps both of them inside. Someone outside knocks in a pattern Mara recognizes.',first_mes:'*Mara lowers the lantern.* "If you are here because of that knocking, answer quickly: did you hear three taps or four?"',mes_example:'<START>\n{{user}}: Why does the tapping matter?\n{{char}}: "Three means shelter. Four means danger."',creator_notes:'Tense travel and mystery.',tags:['mystery','mentor'],extensions:{}}};
connectPersistedSettings($);
file.addEventListener('change', async () => { if(file.files[0]) await load(file.files[0]); }); $('#sample-button').onclick=()=>{text=JSON.stringify(sample);sourcePng=null;$('#card-art').hidden=true;$('#art-placeholder').hidden=false;analyze()}; $('#settings-button').onclick=()=>$('#settings').showModal(); $('#fetch-models-button').onclick=fetchModels; $('#download-button').onclick=downloadJson; $('#download-png-button').onclick=downloadPng; $('#undo-button').onclick=undo;
$('#reanalyze-button').onclick=()=>{gateOpen=true;render();announce('Improvements unlocked.');}; $('#calm').onchange=(e)=>{document.documentElement.style.setProperty('--accent',e.target.checked?'#dfa04f':accent)};
for(const b of $('#model-controls').children)b.onclick=()=>{targetModel=b.dataset.model;localStorage.setItem('cq.model',targetModel);render()}; for(const b of $('#direction-controls').children)b.onclick=()=>{creatorDirection=b.dataset.direction;localStorage.setItem('cq.direction',creatorDirection);render()};
async function load(input){try{sourcePng=null;if(input.type==='image/png'||input.name.endsWith('.png')){const bytes=new Uint8Array(await input.arrayBuffer());text=extractCardJsonFromPng(bytes);sourcePng={bytes,name:input.name};const image=$('#card-art');image.src=URL.createObjectURL(new Blob([bytes],{type:'image/png'}));image.onload=()=>{const colors=accentFromImage(image);accent=colors.accent;if(!$('#calm').checked)document.documentElement.style.setProperty('--accent',colors.accent);document.documentElement.style.setProperty('--bright',colors.bright)};image.hidden=false;$('#art-placeholder').hidden=true}else text=await input.text();analyze()}catch(e){showError(e)}}
function analyze(){try{result=scoreCard(text);applied=[];gateOpen=false;ledger=[`${result.total} · loaded`];empty.hidden=true;review.hidden=false;$('#gate').hidden=false;render();announce(`Scored ${result.total}.`)}catch(e){showError(e)}}
function plan(){return mergeFindings(result.reviewFindings,{targetModel,appliedFindingIds:applied,gateOpen})}
function render(){const p=plan(), score=result.total; $('#score').textContent=score;$('#band').textContent=result.band;$('#headline').textContent=p.blockers.length?`${p.blockers.length} field${p.blockers.length>1?'s':''} block the card — start there.`:p.gate.open?'The queue is open. Shape the remaining details.':'The blockers are clear. Re-analyze to unlock the queue.';$('#summary').textContent=`${result.summary} The score is deterministic; the review below only sequences the work.`;$('#criteria').replaceChildren(...result.criteria.map(c=>el('div','criterion',`<span>${c.label}<br><small>${c.note}</small></span><b>${c.points}/${c.max}</b>`)));setControls();$('#blocker-caption').textContent=p.blockers.length?`${p.blockers.length} blockers`:'';$('#blockers').replaceChildren(...p.blockers.map(card=>fieldCard(card)));$('#gate-title').textContent=p.gate.open?'✓ Unlocked — improvements are actionable':'🔒 Improvements are waiting';$('#gate-copy').textContent=p.gate.reason;$('#locked-improvements').replaceChildren(...p.improvements.map(c=>{const canShowDraft=p.gate.open||c.fixTemplate;const d=el('div',canShowDraft?'':'locked');if(canShowDraft)d.append(fieldCard(c,'improvement'));else d.textContent=`~+${c.leverage} pts · ${c.title}`;return d}));$('#reanalyze-button').disabled=p.blockers.length>0;$('#polish-summary').textContent=`${p.advisories.length} polish notes — advice only, never counted`;$('#advisories').replaceChildren(...p.advisories.map(f=>el('div','advisory',`<b>${f.field}</b> · ${f.summary}`)));$('#ledger').hidden=ledger.length<2;$('#ledger-items').replaceChildren(...ledger.map(x=>el('span','',x)));$('#undo-button').disabled=!previous;$('#download-png-button').disabled=!sourcePng}
function setControls(){for(const b of $('#model-controls').children)b.classList.toggle('active',b.dataset.model===targetModel);for(const b of $('#direction-controls').children)b.classList.toggle('active',b.dataset.direction===creatorDirection)}
function fieldCard(card,kind=''){const node=el('article',`field-card ${kind}`);node.innerHTML=`<div class="field-head"><span class="pill">${card.field}</span><strong>${card.title}</strong><span class="leverage">~+${card.leverage} pts</span></div>`;for(const f of card.findings)node.append(el('div','finding-row',`<b>${f.source}</b><span>${f.summary}</span>`));const area=document.createElement('textarea');area.value=card.fixTemplate||'';area.placeholder='This needs a real character-specific draft. Use the reviewer to write one from the card evidence.';node.append(area);const actions=el('div','actions');const apply=el('button','', 'Apply');apply.disabled=!area.value;apply.onclick=()=>applyCard(card,area.value);const ask=el('button','ask',card.fixTemplate?'Improve with reviewer →':'Draft with reviewer →');ask.dataset.label=ask.textContent;const status=el('div','ask-status');status.setAttribute('role','status');ask.onclick=()=>askReviewer(card,area,ask,status);actions.append(apply,ask);node.append(actions,status);return node}
function applyCard(card,draft){previous={text,applied:[...applied],gateOpen,ledger:[...ledger]};text=JSON.stringify(applySuggestionToCard(text,{field:card.field,draft}),null,2);applied.push(...card.findings.map(f=>f.id));result=scoreCard(text);ledger.push(`+${card.title.toLowerCase()} → ${result.total}`);gateOpen=false;render();announce(`${card.title} applied as one change.`)}function undo(){if(!previous)return;text=previous.text;applied=previous.applied;gateOpen=previous.gateOpen;ledger=previous.ledger;result=scoreCard(text);previous=null;render();announce('Last combined change undone.')}
async function askReviewer(card,area,button,status){const label=button.dataset.label;button.disabled=true;button.textContent='The reviewer is reading…';status.textContent='';status.classList.remove('error');const validFindingIds=card.findings.map(f=>f.id);try{const r=await fetch('/api/ai-review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({card:text,aiConfig:settings(),findings:card.findings,targetField:card.field,validFindingIds,creatorDirection,targetModel,mode:'review'})});const payload=await r.json();if(!r.ok)throw Error(payload.error);const all=payload.suggestions||[];const drafts=filterAiSuggestions(all,new Set(validFindingIds),new Set([card.field]));if(!drafts.length){button.textContent=label;status.classList.add('error');status.textContent=describeReviewerMiss(all,card.field);return}area.value=drafts[0].draft;button.textContent=drafts[0].directionUsed?'AI draft · direction used':'AI draft · grounded';nodeEnable(area)}catch(e){button.textContent=label;status.classList.add('error');status.textContent=e.message||'Reviewer unavailable'}finally{button.disabled=false}}
async function fetchModels(){const button=$('#fetch-models-button'),status=$('#models-status'),list=$('#model-options'),model=$('#ai-model');button.disabled=true;status.textContent='Fetching models…';try{const r=await fetch('/api/models',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({aiConfig:settings()})});const payload=await r.json();if(!r.ok)throw Error(payload.error);const models=Array.isArray(payload.models)?payload.models:[];list.replaceChildren(...models.map(id=>{const option=document.createElement('option');option.value=id;return option}));if(models.length&&!model.value.trim())model.value=models[0];status.textContent=models.length?`Loaded ${models.length} models. Pick one from the Model field.`:'No models returned.'}catch(e){status.textContent=e.message||'Could not fetch models.'}finally{button.disabled=false}}
function nodeEnable(area){area.parentElement.querySelector('.actions button').disabled=!area.value}function settings(){return readAiSettings($)}function announce(m){$('#live').textContent=m}function showError(e){empty.hidden=true;review.hidden=false;$('#headline').textContent="I couldn't read this card.";$('#summary').textContent=e.message||'Check that this is valid JSON or a PNG with embedded card data.';$('#blockers').replaceChildren();$('#gate').hidden=true;announce('Card load error.')}function el(tag,cls,html=''){const n=document.createElement(tag);n.className=cls;n.innerHTML=html;return n}function downloadJson(){blob(text,'character-card.json','application/json')}function downloadPng(){if(!sourcePng)return;blob(embedCardJsonInPng(sourcePng.bytes,text),'character-card.png','image/png')}function blob(data,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
